### ISSUE TITLE
.deb not playable

### ISSUE THREAD

**Issue by italozaina** [pjasicek/OpenClaw#110]
The launcher works fine, but when i hit play got this error below

endoxos@endoxos-Inspiron-N5110 ~ $ clawlauncher
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319
WARN: [RunGameEngine] Failed to set high priority class to this process
INFO: Looking for: /home/endoxos/.config/openclaw/config.xml
INFO: Expecting config.xml in path: /home/endoxos/.config/openclaw/config.xml
INFO: Loaded with:
	Config File: /home/endoxos/.config/openclaw/config.xml
	Saves File: /home/endoxos/.config/openclaw/SAVES.XML
INFO: >>>>> Initializing display...
endoxos@endoxos-Inspiron-N5110 ~ $ INFO: Display successfully initialized.
INFO: >>>>> Initializing audio...
INFO: Audio successfully initialized.
INFO: >>>>> Initializing font...
INFO: Font successfully initialized...
INFO: >>>>> Initializing resource cache...
INFO: Resource cache successfully initialized
INFO: >>>>> Loading actor prototypes...
INFO: Actor prototypes loaded successfully.
ERROR: [Initialize] Error while loading /home/endoxos/.config/openclaw/SAVES.XML: Failed to open file
ERROR: [VCreateGameAndView] Could not initialize Claw Game Logic.
ERROR: [Initialize] Failed to initialize game logic.
ERROR: [RunGameEngine] Failed to initialize. Exiting.

**Comment by pjasicek** [comment]
That's weird. Can do "ls -al /home/endoxos/.config/openclaw" and post it here please ?

**Comment by italozaina** [comment]
endoxos@endoxos-Inspiron-N5110 ~ $ ls -al /home/endoxos/.config/openclaw
total 12
drwxr-xr-x  2 endoxos endoxos 4096 Ago 23 15:57 .
drwxr-xr-x 59 endoxos endoxos 4096 Ago 23 15:57 ..
-rw-r--r--  1 endoxos endoxos 2492 Ago 23 15:58 config.xml

**Comment by pjasicek** [comment]
Oh. When did you try it ? I added postinst script few minutes ago which copies the SAVES.XML properly.

**Comment by pjasicek** [comment]
Or you can try my package: https://github.com/pjasicek/OpenClaw/releases

**Comment by italozaina** [comment]
download .deb 5 minutes ago

**Comment by italozaina** [comment]
i ll figure out what happens. Maybe it just here

**Comment by pjasicek** [comment]
if you do "cp /usr/share/openclaw/SAVES.XML ~/.config/openclaw" it will work just fine. But I need to find WHY this happened to you.

**Comment by pjasicek** [comment]
Try it now please with https://github.com/pjasicek/OpenClaw/releases/download/v0.0/openclaw_1.0-1.deb

But first please uninstall the package - sudo apt remove openclaw and remove the config dir - rm -rf ~/.config/openclaw

Thanks for testing

**Comment by italozaina** [comment]
Perfect, now this .deb work fine
Thanks
