### ISSUE TITLE
Missing DLL

### ISSUE THREAD

**Issue by Matthaiks** [pjasicek/OpenClaw#112]
openclaw_Windows requires msvcr120d.dll to run.

**Comment by pjasicek** [comment]
Thanks for report. Looks like SDL2_gfx has a hidden dependency on a library built in debug mode, Interesting.

**Comment by pjasicek** [comment]
Updated Windows package in Release section. Try it now please.

**Comment by Matthaiks** [comment]
Crash on startup, but this one works:
http://dllworld.org/msvcr120d-dll/

**Comment by pjasicek** [comment]
Thank you, updated with the version you provided.
