### ISSUE TITLE
Level 7 black screen on Ubuntu

### ISSUE THREAD

**Issue by cipiricus** [pjasicek/OpenClaw#118]
![1](https://user-images.githubusercontent.com/10581339/30772713-1d5772c0-a06a-11e7-9f22-8ecc076248d9.png)
![2](https://user-images.githubusercontent.com/10581339/30772714-1d5dc5ee-a06a-11e7-83f6-4ebce0b39ae7.png)

**Comment by pjasicek** [comment]
Thanks for report. This only happens after finishing level 7, right ?

**Comment by cipiricus** [comment]
Other levels works fine
