### ISSUE TITLE
[Level 6] Crashes after boss fight

### ISSUE THREAD

**Issue by maxshayne** [pjasicek/OpenClaw#129]
OpenClaw 1.0.2
Windows 10, ver. 17134.48, x64.
Happens twice before loading level 7. 

![screenshot at 01-13-52](https://user-images.githubusercontent.com/16781629/41205176-8ac470bc-6d18-11e8-9fcd-b8348820f010.png)

**Comment by maxshayne** [comment]
Oops. Didn't noticed that levels 7-14 still under development.
Any chances they will be available soon?

**Comment by pjasicek** [comment]
Thanks for the report, my bad. Fixed it in https://github.com/pjasicek/OpenClaw/commit/ad9206ff44f9feefaa090eadcc7a135da31e7818

- levels 1-10 are implemented, 11-14 are not (not sure if they ever will be)

**Comment by pjasicek** [comment]
https://github.com/pjasicek/OpenClaw/releases/tag/v0.3

- To keep existing saves, just copy the SAVES.XML from previous version to the new one
