### ISSUE TITLE
Cannot change controls

### ISSUE THREAD

**Issue by McSaks** [pjasicek/OpenClaw#133]
Nothing happens when I choose Options > Controls. Is it possible to change control keys?
`Ctrl` key seems not to work unless an arrow key is pressed — that’s annoying.

**Comment by pjasicek** [comment]
"Controls" page is not implemented so all controls remain hardcoded as they are now.

Now sure what you mean by "Ctrl key seems not to work unless an arrow key is pressed" - works for me both on windows and linux. Ctrl key is used for attacking and all attacks work fine - normal/jump/duck attacks.

**Comment by McSaks** [comment]
That means that I can’t attack while standing still, only being running. I can, though, use (`Alt`) and change (`Shift`) weapon. Only `Ctrl` doesn’t work.
I’m using Ubuntu.

**Comment by pjasicek** [comment]
well it works on my linux vmware machine (also ubuntu) - so not sure what the problem is

**Comment by McSaks** [comment]
Ok, recoded `HandleAction(ActionType_Attack)` to another key. Works fine.
