### ISSUE TITLE
Problem with start game

### ISSUE THREAD

**Issue by patitocarei** [pjasicek/OpenClaw#165]
Hi, first thank for your work, is awesome!
I use Raspberry pi 3 b+ with retropie and raspbian lite, I have all requeriments (SDL2) and good compiled version. 
My problem is after launch "clawlauncher", press play and my game start in loading screen level 13 Tiger Island, after the load the game crash. I tried compiling again and another file "CLAW.REZ".
Don't have much knowledge of ubuntu, but I don't know what happens.
Thank you, and sorry for my english.

**Comment by pjasicek** [comment]
Hi, sorry about that - I left some development config options in one of the last commits. It should work now if you pull latest commit - you should get to the menu :-)

But please keep in mind that only the first 12 levels are implemented, levels 13 and 14 are not done yet. Also some of the last bosses are not implemented.

**Comment by YosefX01** [comment]
i have a problem in opening game because mono gives me this error
![Screenshot from 2022-02-12 00-48-43](https://user-images.githubusercontent.com/90049570/153681184-8fe87338-4ff8-48b6-af63-f564e363a63b.png)

**Comment by YosefX01** [comment]
please any help and ty ^^

**Comment by pjasicek** [comment]
From the error message it should be obvious - openclaw binary (the game executable) needs to be in the same folder as the launcher (if you want to run the game via the launcher)

So once you build the game, move the openclaw binary to the Build_Release folder

**Comment by YosefX01** [comment]
some explain i wanna to understand step by step because i'm stuck and ty :D
my distro : Zorin OS 16 cor
![Screenshot from 2022-02-12 16-17-05](https://user-images.githubusercontent.com/90049570/153714918-6993146c-34eb-4595-aded-2821d01a3028.png)
e

**Comment by pjasicek** [comment]
Follow the steps in README.md to build the game (binary "openclaw"), then copy that binary to Build_Release folder.

If something doesn't work for you, ask specifically.

**Comment by pjasicek** [comment]
```
cd OpenClaw
mkdir build
cd build
cmake ..
make -j16
cp openclaw ../Builld_Release
cd ../Build_Release
mono ClawLauncher.exe
or
./openclaw
```

**Comment by YosefX01** [comment]
![Screenshot from 2022-02-13 17-01-18](https://user-images.githubusercontent.com/90049570/153759289-20bcd170-e581-451b-8716-632c749c13fa.png)

**Comment by pjasicek** [comment]
It is C++ project, you need to install C++ compiler. On debian distros it is in 'build-essentials' package, it may be different on your distro.

**Comment by YosefX01** [comment]
maybe my pc isn't comblibitable with this kind of games and the problem is from my processor

**Comment by jadsonosd** [comment]
Hum, cool.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jadsonosd** [comment]
Very nice, nice night.

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by YosefX01** [comment]
but the same issue appears the same bin error
ok ty for helping me maybe the game won't run
