### ISSUE TITLE
CLAW.REZ where is the file

### ISSUE THREAD

**Issue by YosefX01** [pjasicek/OpenClaw#170]
the file CLAW.REZ isn't here and the game closes

**Comment by pjasicek** [comment]
Please read the README.md next time, it is covered there.

You can get it either from official game or from my older release - https://github.com/pjasicek/OpenClaw/releases/download/v0.3/OpenClaw_v1.03.zip

**Comment by YosefX01** [comment]
i read it but idk why it missed REZ file xD

**Comment by YosefX01** [comment]
anyway it works but it still didn't work at running :>

**Comment by YosefX01** [comment]
butwhy old release is so buggy :( ?

**Comment by YosefX01** [comment]
gravity is bad and ladder when he get up it loops all time or fall and when die and use any arrow it won't reset player to checkpoint xD

**Comment by pjasicek** [comment]
* Gravity is bad - what do you mean ? What is bad about gravity ?
* What is wrong with the end ladder ? There is one minor issue when holding arrow up when on the end of the ladder, Claw tries to keep climbing, but that's more of a cosmetic issue imo.
![image](https://user-images.githubusercontent.com/12572760/166195344-c19ec2aa-3176-44a3-be5c-8d7e35511c56.png)
* What you fall and die and use any arrow it it doesn't bug anything for me. Try to give me a reproducible example.

**Comment by jadsonosd** [comment]
I liked this photo :D

**Comment by YosefX01** [comment]
> * Gravity is bad - what do you mean ? What is bad about gravity ?
> 
>     * What is wrong with the end ladder ? There is one minor issue when holding arrow up when on the end of the ladder, Claw tries to keep climbing, but that's more of a cosmetic issue imo.
>       ![image](https://user-images.githubusercontent.com/12572760/166195344-c19ec2aa-3176-44a3-be5c-8d7e35511c56.png)
> 
>     * When you fall and die and use any arrow it it doesn't bug anything for me. Try to give me a reproducible example.

i loved this angry photo xD
