### ISSUE TITLE
Legality

### ISSUE THREAD

**Issue by cyd15x** [pjasicek/OpenClaw#175]
Hi, is this game completely freeware? or sometihng like abandonware

**Comment by pjasicek** [comment]
Hi, could you elaborate please ?

OpenClaw source code is open under attached GPLv3 license - https://github.com/pjasicek/OpenClaw/blob/master/LICENSE.txt

CLAW.REZ (original game's assets) is property of Warner Bros (originally by Monolith Games which was bought by WB in 2004).

**Comment by cyd15x** [comment]
so it is legal to play game with original claw.rez file?

**Comment by pjasicek** [comment]
If you obtained the CLAW.REZ file by buying the original game in some legal way (e.g. gog.com), then yes, it is strictly legally speaking 100% legal. It follows the same philosophy as OpenTTD.

**Comment by cyd15x** [comment]
Thanks for answers

**Comment by dalbert12** [comment]
> If you obtained the CLAW.REZ file by buying the original game in some legal way (e.g. gog.com), then yes, it is strictly legally speaking 100% legal. It follows the same philosophy as OpenTTD.

i am curious this same as topic owner, i dont understand that you using " claw.rez " file with owners permission?

**Comment by pjasicek** [comment]
> > If you obtained the CLAW.REZ file by buying the original game in some legal way (e.g. gog.com), then yes, it is strictly legally speaking 100% legal. It follows the same philosophy as OpenTTD.
> 
> i am curious this same as topic owner, i dont understand that you using " claw.rez " file with owners permission?

Could you elaborate please ? I am not versioning the CLAW.REZ in this repository. It is up to everyone to get their own copy of the CLAW.REZ (be it "legal" or otherwise :) )

**Comment by pjasicek** [comment]
This is also explicitly stated in the project's README.md:

https://github.com/pjasicek/OpenClaw#building-and-running

**Comment by dalbert12** [comment]
didnt read readme file now i see thanks

**Comment by pjasicek** [comment]
No problem.
