### ISSUE TITLE
CLAW.REZ Resource file for assets isn't found

### ISSUE THREAD

**Issue by pavly-gerges** [pjasicek/OpenClaw#176]
Today, i tried the OpenClaw platformer, however found the resource file `CLAW.REZ` not there in `Build_Release`, so i copied it from older versions, and found that it was ignored by `.gitignore`, are there any reasons to not add the resource file to the build and ignore it on purpose ?

**Comment by pjasicek** [comment]
Hi, your point was adressed in previous ticket - https://github.com/pjasicek/OpenClaw/issues/175

The reason it is not included in this repository is that the CLAW.REZ is part of the original game and so there are legal / copyright ramifications, I cannot publicly add it to this repository. It is up to you to get the CLAW.REZ from any sources you see fit. This point is described in the repository's README.md.

**Comment by pavly-gerges** [comment]
Alright, thank you, you are doing a great a job on this game btw, keep up, it will be good to add a contribution guide and code of conduct to this project, for example, the first idea came to my mind when writing the contribution guide is to list down the main API used to write this game (SDL2 in this case), the main design patterns addressed in your code (mainly GameStates and GameLogics) and the third parties besides the build script...

Anyway closing this issue now, thank you !
