### ISSUE TITLE
Roadmap 2: What's next

### ISSUE THREAD

**Issue by pjasicek** [pjasicek/OpenClaw#72]
**Current state:**

Levels 1-4 are good enough for me - there are no game-breaking major issues that I know of. The game is stable and does not crash at all in the first 4 levels.

FPS is good enough at the moment - 1100 - 1300 FPS on GTX 760 GPU and i5 3.4GHz CPU. But FPS varies from level to level.

Windows - OK
Linux (all distros) - OK
MacOS - OK
Android - Compilable, playable but not yet supported
iOS (iPad + iPhone) - Not supported, but feasible
Windows Phone - Not supported, not plans to support it

Overall, the progress over 3 months was tremendous from my point of view (over 20k C++ LoC were written and over 15k XML LoC were created). If I can push myself the same way in the following months at l will be very happy with myself.

**Future plans: (1.7. - 1.10. 2017)**

- Implement levels 5, 6
- Support android platform - make APK and distribute it freely on Google store
- Enhance boss logics
- Attempt to add cutscene cinematics

**Comment by pjasicek** [comment]
Level 5 done !

**Comment by pjasicek** [comment]
Level 6 done !

**What next:**

- Make ingame menu screen after pressing escape
- Make end screen after defeating level 6 boss (implementing levels 1-6 was the main goal) and then move back to main screen
- Focus on various bugfixes (there are not so many) throughout the levels
- Enhance boss logics (some of them have the ability to jump back instead of taking damage and so on)
- Compile and store on github the whole Android toolchain and precompiled libraries
- Figure out controls on Android
- Attempt to add cutscene cinematics (ffmpeg library is needed for this which is a bit collosal)

**Comment by pjasicek** [comment]
Ingame menu done. This time I was really glad when I invested quite a lot of time in proper design of Main Menu implementation in first place - 99% of the ingame menu is based on that.

**Comment by pjasicek** [comment]
**Plans for now:**

- Make captainclaw-1.0-1.deb package for debian distribution
- Make captainclaw-1.0-1.rpm package for fedora/centos distribution

**Comment by jstasiak** [comment]
Regarding distributing the application to users - I'd be happy to help with a [Homebrew](https://brew.sh/) package for mac os. There are two considerations here:
* there need to be version numbers that can be used in package definition
* I think the name ``captainclaw`` is too generic (there's no way to distinguish the original game and this project by name alone which may create confusion and maybe even a legal liability)

**Comment by pjasicek** [comment]
it should probably be called "openclaw" or something like that. TTD open source project named itself also "OpenTTD" and there was no problem with that. I am welcome to any suggestions.

As captainclaw being too generic - there is no linux version of original CaptainClaw so it should not be a problem, but on Windows it is undistinguishable.

**Comment by jstasiak** [comment]
Yeah, although I meant it more in a platform-independent project name way. Regardless - I really like openclaw, it has a nice ring to it.

**Comment by pjasicek** [comment]
As of now I am officially happy with the result. I played first 2 levels and I could not really see any noticable difference between original game and this reimplementation regarding gameplay. This week I will make packages for distributions - deb/rpm/msi.

**Comment by pjasicek** [comment]
Project renamed to "OpenClaw"
